fix PATH issue for bazel to run

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -11,7 +11,8 @@ if [ -z "$uidentry" ] ; then
     if [ -w /etc/passwd ] ; then
         echo "$myuid:x:$myuid:$mygid:anonymous uid:/home/$NB_USER:/bin/false" >> /etc/passwd
     else
-        echo "Container ENTRYPOINT failed to add passwd entry for anonymous UID"
+        echo "ERROR:Container ENTRYPOINT failed to add passwd entry for anonymous UID"
+        exit 1
     fi
 fi
 
